[package]
name = "inventor-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
inventor-core = { path = "../crates/inventor-core", features = ["fuzzing"] }

[workspace]
members = ["."]

[[bin]]
name = "container"
path = "fuzz_targets/container.rs"
test = false
doc = false
bench = false

[[bin]]
name = "streams"
path = "fuzz_targets/streams.rs"
test = false
doc = false
bench = false
