"""Check canonical license texts, generated notices, and package metadata."""
import hashlib
import json
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parents[1]
PROJECT_LICENSE = 'PolyForm-Noncommercial-1.0.0 AND MIT'
DISTRIBUTION_LICENSE = PROJECT_LICENSE + ' AND Apache-2.0 AND BSD-3-Clause AND CC-BY-4.0 AND Zlib'
PINNED_TEXTS = {
    'licenses/PolyForm-Noncommercial-1.0.0.md': 'c0ea4a896d2c8c394b29f9427589996db826cd501c512279ff0ed3ef48fabbe5',
    'licenses/inventor-kit-legacy-MIT.txt': 'c631eb20a0675add35e49625d3bf3952fe3b0923d98eb050e775c6acfbeaf3be',
    'licenses/CC-BY-4.0.txt': 'd557539df68e771cc1eedcc91d13f70fca930e508d11eedcafa4b15db49e3744',
}
REQUIRED_NOTICES = (
    'Required Notice: inventor-kit is licensed by UnRobotics Inc. (https://www.un-robotics.com/).',
    'Required Notice: inventor-kit 0.3.0 and later offer new material under PolyForm Noncommercial 1.0.0; separate commercial licenses are available.',
)


def license_paths(root=ROOT):
    return ['LICENSE', 'COMMERCIAL-LICENSE.md', 'THIRD_PARTY_NOTICES.md'] + [
        p.relative_to(root).as_posix() for p in sorted((root/'licenses').iterdir())
        if p.is_file() and p.suffix in {'.txt', '.md', '.json'}]


def notice_bundle(root=ROOT, *, viewer=False):
    paths = (['LICENSE', 'COMMERCIAL-LICENSE.md', *list(PINNED_TEXTS)[:2]]
             if viewer else license_paths(root))
    preamble = (
        'Generated by scripts/sync_license_notices.py; do not edit this copy.\n'
        'Canonical repository files named below are reproduced in this notice.\n'
        'Relative references refer to the inventor-kit source distribution.\n'
        'Repository: https://github.com/monozukuri-ai/inventor-kit\n'
    )
    return (preamble + ''.join('\n===== ' + p + ' =====\n\n' +
                              (root/p).read_text(encoding='utf-8') for p in paths)).encode()


def check_pinned_texts(read):
    for path, digest in PINNED_TEXTS.items():
        if hashlib.sha256(read(path)).hexdigest() != digest:
            raise ValueError('Changed canonical license text: ' + path)


def check_archive_licenses(contents, meta, prefix, root=ROOT):
    """Check exact metadata paths, not a permissive archive suffix match."""
    expected = set(license_paths(root))
    declared = meta.get_all('License-File', [])
    if len(declared) != len(set(declared)) or set(declared) != expected:
        raise ValueError('Unexpected License-File declarations')
    for path in sorted(expected):
        full = prefix + path
        if full not in contents:
            raise ValueError('Missing license/notice: ' + full)
        if contents[full] != (root/path).read_bytes():
            raise ValueError('Stale license/notice: ' + full)
    check_pinned_texts(lambda p: contents[prefix+p])


def check(root=ROOT):
    check_pinned_texts(lambda p: (root/p).read_bytes())
    for path in ('LICENSE', 'README.md', 'README.ja.md'):
        text = (root/path).read_text(encoding='utf-8')
        if not all(n in text.splitlines() for n in REQUIRED_NOTICES):
            raise ValueError('Missing Required Notice: ' + path)
    project = tomllib.loads((root/'pyproject.toml').read_text())['project']
    workspace = tomllib.loads((root/'Cargo.toml').read_text())['workspace']['package']
    if project['license'] != DISTRIBUTION_LICENSE or workspace['license'] != PROJECT_LICENSE:
        raise ValueError('Unexpected project license expression')
    declared = {p.relative_to(root).as_posix() for pattern in project['license-files']
                for p in root.glob(pattern) if p.is_file()}
    if declared != set(license_paths(root)):
        raise ValueError('pyproject license-files do not cover the canonical files')
    for name in ('inventor-core', 'inventor-py'):
        base = root/'crates'/name
        package = tomllib.loads((base/'Cargo.toml').read_text())['package']
        if package['license'] != {'workspace': True} or package['version'] != project['version']:
            raise ValueError('Unexpected crate license/version: ' + name)
        if (base/'LICENSE').read_bytes() != notice_bundle(root):
            raise ValueError('Stale crate license bundle: ' + name)
    if (root/'viewer/LICENSE.txt').read_bytes() != notice_bundle(root, viewer=True):
        raise ValueError('Stale viewer license notice')
    viewer = json.loads((root/'viewer/package.json').read_text())
    lock = json.loads((root/'viewer/package-lock.json').read_text())
    if (viewer['license'] != PROJECT_LICENSE or viewer['version'] != project['version']
            or lock['version'] != project['version']
            or lock['packages']['']['license'] != PROJECT_LICENSE
            or lock['packages']['']['version'] != project['version']):
        raise ValueError('Unexpected viewer license/version')
    catalog = json.loads((root/'licenses/rust-dependencies.json').read_text())
    locked = tomllib.loads((root/'Cargo.lock').read_text())['package']
    expected = {(p['name'], p['version'], p.get('checksum')) for p in locked if p.get('source')}
    rows = catalog['packages'] + catalog['excluded']
    if any((p['name'], p['version']) != ('r-efi', '6.0.0') or not p['reason'] for p in catalog['excluded']):
        raise ValueError('Unreviewed Rust notice exclusion')
    actual = {(p['name'], p['version'], p['checksum']) for p in rows}
    if actual != expected or len(actual) != len(rows):
        raise ValueError('Rust notice inventory does not match Cargo.lock')
    if hashlib.sha256((root/'licenses/rust-dependencies.txt').read_bytes()).hexdigest() != catalog['notices_sha256']:
        raise ValueError('Rust notice catalog hash mismatch')
    return project['version']


if __name__ == '__main__':
    print('License checks passed for inventor-kit ' + check())
