"""Regenerate self-contained crate/viewer notices; optionally refresh Cargo notices."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess
import tomllib

from check_license import ROOT, check_pinned_texts, notice_bundle

# A new license combination requires review, especially additional AND terms.
REVIEWED_LICENSES = {
    'MIT', 'MIT OR Apache-2.0', 'Apache-2.0 OR MIT', 'Apache-2.0 / MIT',
    'MIT/Apache-2.0', 'Unlicense OR MIT', 'MIT OR Zlib OR Apache-2.0',
    '0BSD OR MIT OR Apache-2.0', '(Apache-2.0 OR MIT) AND BSD-3-Clause',
    '(MIT OR Apache-2.0) AND Unicode-3.0', 'Apache-2.0 WITH LLVM-exception',
    'Zlib',
}


def refresh_rust(root=ROOT):
    metadata = json.loads(subprocess.check_output(
        ['cargo', 'metadata', '--locked', '--offline', '--format-version', '1'], cwd=root))
    locked = tomllib.loads((root/'Cargo.lock').read_text())['package']
    checksums = {(p['name'], p['version']): p['checksum'] for p in locked if p.get('checksum')}
    packages, sections, excluded = [], [], []
    for p in sorted(metadata['packages'], key=lambda p: (p['name'], p['version'])):
        if p['source'] is None:
            continue
        if (p['name'], p['version']) == ('r-efi', '6.0.0'):
            excluded.append({'name': p['name'], 'version': p['version'],
                             'checksum': checksums[p['name'], p['version']],
                             'reason': 'UEFI-only getrandom dependency; no supported inventor-kit distribution targets UEFI'})
            continue
        if p['license'] not in REVIEWED_LICENSES:
            raise ValueError(f'Unreviewed dependency license: {p["name"]}: {p["license"]}')
        base = Path(p['manifest_path']).parent
        candidates = sorted(f for f in base.iterdir() if f.is_file()
                            and f.name.upper().startswith(('LICENSE', 'COPYING', 'COPYRIGHT', 'NOTICE')))
        license_source = 'registry package'
        if not candidates and p['name'] in {'acis-core', 'acis-py-bridge'}:
            # These MIT registry crates omit the text. Preserve the cq-acis
            # notice already maintained by this repository, without changing it.
            base = root
            candidates = [root/'licenses/cq-acis-MIT.txt']
            license_source = 'preserved cq-acis notice; registry package omits license text'
        if not candidates:
            raise ValueError('No license text for ' + p['name'])
        # Select MIT when offered; retain mandatory data/Unicode licenses and notices.
        mit = [f for f in candidates if 'MIT' in f.name.upper()]
        files = ([f for f in candidates if f in mit or
                  any(s in f.name.upper() for s in ('WHATWG', 'UNICODE', 'COPYRIGHT', 'NOTICE'))]
                 if mit and 'MIT' in (p['license'] or '') else candidates)
        if p['name'] == 'zstd-sys':
            files.append(base/'zstd/LICENSE')
        entries = []
        for f in sorted(set(files)):
            data = f.read_bytes()
            path = f.relative_to(base).as_posix()
            entries.append({'path': path, 'sha256': hashlib.sha256(data).hexdigest()})
            sections.append(f'===== {p["name"]} {p["version"]}: {path} =====\n\n' + data.decode('utf-8').rstrip() + '\n')
        packages.append({'name': p['name'], 'version': p['version'], 'source': p['source'],
                         'checksum': checksums[p['name'], p['version']],
                         'upstream_license': p['license'], 'license_source': license_source,
                         'license_files': entries})
    data = ('Locked Cargo dependency notices, including build and target-specific tools.\n'
            'Generated by scripts/sync_license_notices.py --refresh-rust.\n'
            'MIT is selected where offered; mandatory additional licenses are retained.\n\n'
            + '\n'.join(sections)).encode()
    (root/'licenses/rust-dependencies.txt').write_bytes(data)
    (root/'licenses/rust-dependencies.json').write_text(json.dumps({
        'schema_version': 1, 'notices_sha256': hashlib.sha256(data).hexdigest(),
        'packages': packages, 'excluded': excluded}, indent=2) + '\n')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--refresh-rust', action='store_true', help='Read locked registry source notices (requires cargo fetch)')
    args = parser.parse_args()
    check_pinned_texts(lambda p: (ROOT/p).read_bytes())
    if args.refresh_rust:
        refresh_rust()
    for name in ('inventor-core', 'inventor-py'):
        (ROOT/'crates'/name/'LICENSE').write_bytes(notice_bundle())
    (ROOT/'viewer/LICENSE.txt').write_bytes(notice_bundle(viewer=True))
    print('Updated crate and viewer license notices; rebuild viewer assets next')


if __name__ == '__main__':
    main()
